fix: make SET system type case-insensitive
dolthub/go-mysql-server pull request #2702
Opened 2024-10-15 09:41 UTC by fanyang01

Resolves #2701

2024-10-16 20:21 UTC, jycor requested changes
Thanks for the contribution!
MySQL does use the `utf8mb4_0900_ai_ci` collation for `@@sql_mode`, so we should change that, but only that variable and not all system set type

2024-10-17 02:19 UTC, fanyang01 commented on sql/types/system_set.go
> +	return systemSetType{MustCreateSetType(values, sql.Collation_ascii_general_ci), varName}
Hi @jycor, thank you for your review! I'm uncertain about which collation should be used for other system variables. Could you please direct me to where I can find MySQL's implementation?

```sql
mysql> set global log_output = 'table,file';
Query OK, 0 rows affected (0.00 sec)

mysql> select @@global.log_output;
+---------------------+
| @@global.log_output |
+---------------------+
| FILE,TABLE          |
+---------------------+
1 row in set (0.00 sec)

mysql> set global log_output = default;
Query OK, 0 rows affected (0.00 sec)

mysql> select @@global.log_output;
+---------------------+
| @@global.log_output |
+---------------------+
| FILE                |
+---------------------+
1 row in set (0.00 sec)

mysql> set global protocol_compression_algorithms = 'zLIB,Zstd';
Query OK, 0 rows affected (0.01 sec)

mysql> select @@global.protocol_compression_algorithms;
+------------------------------------------+
| @@global.protocol_compression_algorithms |
+------------------------------------------+
| zLIB,Zstd                                |
+------------------------------------------+
1 row in set (0.01 sec)

mysql> set global protocol_compression_algorithms = default;
Query OK, 0 rows affected (0.00 sec)

mysql> select @@global.protocol_compression_algorithms;
+------------------------------------------+
| @@global.protocol_compression_algorithms |
+------------------------------------------+
| zlib,zstd,uncompressed                   |
+------------------------------------------+
1 row in set (0.00 sec)
```

2024-10-17 03:04 UTC, fanyang01 commented on sql/types/system_set.go
> +	return systemSetType{MustCreateSetType(values, sql.Collation_ascii_general_ci), varName}
I have learned the following facts from MySQL's source code:
- `protocol_compression_algorithms` is [defined to be a `Sys_var_charptr`](https://github.com/mysql/mysql-server/blob/61a3a1d8ef15512396b4c2af46e922a19bf2b174/sql/sys_vars.cc#L7296) and is [validated](https://github.com/mysql/mysql-server/blob/61a3a1d8ef15512396b4c2af46e922a19bf2b174/sql-common/compression.cc#L40) using the case-insensitive collation of `latin1`.
- `sql_mode` and `log_output` are defined as [`Sys_var_set`](https://github.com/mysql/mysql-server/blob/61a3a1d8ef15512396b4c2af46e922a19bf2b174/sql/sys_vars.h#L1624) and is [parsed](https://github.com/mysql/mysql-server/blob/61a3a1d8ef15512396b4c2af46e922a19bf2b174/sql/strfunc.cc#L88) using [the `to_upper` function of `system_charset_info`](https://github.com/mysql/mysql-server/blob/61a3a1d8ef15512396b4c2af46e922a19bf2b174/sql/strfunc.cc#L127).

2024-10-17 18:02 UTC, jycor approved these changes
Thanks for the changes and even digging into the MySQL source code.
LGTM!

2024-10-17 18:02 UTC, merged